### ISSUE TITLE
Correct module name or link for 'nat' - ModuleNotFoundError

### ISSUE THREAD

**Issue by GenTxt** [ruthschulz/Book_Summarizer#5]
Hi

Thanks for the interesting repo. I've cloned, updated paths, and installed all listed requirements but when I run 'python book_summarizier.py' the following missing module error is generated:

Traceback (most recent call last):
  File "book_summarizer.py", line 22, in <module>
    from abstractive_summarizer import create_abstractive_summary_book
  File "/home/pixelhead/Book_Summarizer/Book_Summarizer/abstractive_summarizer.py", line 13, in <module>
    from nats.pointer_generator_network.model import *
ModuleNotFoundError: No module named 'nats.pointer_generator_network'

I've searched for several modules and installed 'nats-python' but the error persists.
Is there a correct pip or apt install command or site where I can download the missing package?

Thanks

**Comment by ruthschulz** [comment]
Hi, thanks for your interest in the repo.
I am currently working on the instructions for using the repo in the Readme of the dev-clean_code-20191008 branch.
Otherwise, I'll be merging this back into the main branch by next week.

**Comment by ruthschulz** [comment]
Hi, I have updated master now, and also included a notebook showing an example set up and run.
Let me know if you still can't get it to work for you.

**Comment by GenTxt** [comment]
Thanks. I downloaded the dev version you mentioned and it appears to be
working fine for the most part except that it didn't generate an
abstraction summary similar to the 11.txt you provided in the repo.

I will download the latest master and test later.

Cheers

**Comment by GenTxt** [comment]
Current master version works great. Just need to remember two empty lines before the chapter headings and all examples work 100%

Would be nice to see this on a gpu using a larger GPT2 or similar language model.

Thanks again

**Comment by ruthschulz** [comment]
Great to hear. Yes, I wanted to implement a smarter way to divide into chapters, but ran out of time. Maybe later. And yes, the pointer-generator model used here for the abstractive summarizer ends up being similar to an extractive summarizer because it tends to copy from the text. I looked into using GPT2, but that just makes up nonsense sentences that are a continuation of whatever you put into it, so is not a great summarizer, more like a related story.
